version: '3.9'

services:
  test_postgres_db:
    image: 'postgres:16.9-alpine'
    container_name: 'test_postgres_db'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test-minimal-api
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 2s

  test_flyway:
    image: 'flyway/flyway:11-alpine'
    container_name: 'flyway_migrations'
    volumes:
      - './infra/migrations:/flyway/sql'
    command: -url=jdbc:postgresql://test_postgres_db/test-minimal-api -user=postgres -password=postgres -connectRetries=60 migrate